export {default as App} from  "./App"
export {default as Header} from "./Header"
export {default as Navbar} from "./Navbar"
export {default as About } from "./About"
export {default as Skills} from "./Skills"
export {default as Projects} from "./Projects"
export {default as Footer} from "./Footer"